name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: make application.yml
      run: |
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.APPLICATION_PROPERTIES }}" >> ./application.yml
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew bootJar
    
    - name: Web Docker build and push
      env: 
        TAG: github.base_ref
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/${{ TAG }} .
        docker push ${{ secrets.DOCKER_REPO }}/${{ TAG }}
